# This is a basic workflow that is manually triggered

name: module3_task0

# Controls when the action will run. Workflow runs on push or daily at 3:00 PM
on:
  push:
  schedule:
    - cron: '0 15 * * *'


jobs:
  # This workflow contains a single job called "reset"
  reset:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: running make help
        run: make help -C module3_task0
